### PR TITLE
chore: show region around BRCA2 in lollipop example

### PR DESCRIPTION
**Pull request by sehilyi**
After:
Screen Shot 2021-12-16 at 10 53 02 AM

Before:
Screen Shot 2021-12-16 at 10 54 45 AM

@manzt Is there a way to locally run a documentation website after making changes?

### CODE REVIEW

**Review by manzt — APPROVED** [review]
LGTM!

**Comment by sehilyi** [comment]
Great! Also, is there a way to locally run a documentation website after making changes?

**Comment by manzt** [comment]
Yes, should be possible with:

```
make doc
```

and then opening the contents of the generated directory in the browser

**Comment by sehilyi** [comment]
Thanks, gh-actions looks working without any issues.

**Pull request merged**
