### PR TITLE
refactor: use schemapi from altair submodule

### PR DESCRIPTION
**Pull request by manzt**
Prior to this PR, the code in `tools/schemapi/*` was copied from Altair. This PR adds Altair as a git [submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules), and then imports the code from `tools/altair/tools/schemapi`. 

I believe this is the "correct" way to keep things in sync with Altair (and allow us to pin versions if necessary), but perhaps it's overboard. Open to suggestions.

### CODE REVIEW

**Review by sehilyi — APPROVED** [review]
I like the idea of using a submodule, more than the previous approach. 

I think we can also consider pinning a specific branch of released Altair versions, such as [v4.2.X](https://github.com/altair-viz/altair/tree/v4.2.X) which is dedicated for v4.2.0 and any future patches (they create a new branch when bumping a version). For example, we can run

```sh
git config -f .gitmodules submodule.tools/altair.branch v4.2.X

git submodule update --remote 
```

Changes on `.gitmodules`:
```diff
[submodule "tools/altair"]
	path = tools/altair
	url = https://github.com/altair-viz/altair.git
+	branch = v4.2.X
```

This way, we ensure that we track a stable version of Altair, and I think someone can more clearly see which Altair version we use through the `.gitmodules` file.

**Comment by manzt** [comment]
I think it should be find to track commits on the `main` branch, but I see you point.The git submodule doesn't follow a branch in realtime but pins a specific commit. You must manually run `git submodule update` to update to the latest commit on the branch it tracks.

The other thing is that this isn't really following a version of Altair, but a version of an internal dependency (`schemapi`) so I'm not sure if following semver for Altair makes sense (since the internals could theoretically change).

**Comment by sehilyi** [comment]
Yes, it makes sense to track a specific commit. I guess I wondered about (1) when to pull the updates from the submodule to this repo (e.g., whenever there is a major update on `schemapi` or a new Altair version release?) and (2) if the `schemapi` in the `main` branch can be considered a stable code. Since (I believe) `schemapi` in a specific branch (e.g., v4.2.X) is used for the released Altair, I think we can consider it to be stable and is dedicated for v4.2.0. But, given that `schemapi` is not updated that frequently (i.e., I see there are no updates since v4.2.0 in December last year), this does not matter that much.

**Comment by manzt** [comment]
I think I'm going to merge this for now, and we can pin a specific branch if it becomes an issue!

**Pull request merged**
